### PR TITLE
fix: allow failure reading config file

### LINKED ISSUE #20: Previous PR breaks the CLI
Changes submitted [here](https://github.com/packethost/packet-cli/pull/17) are breaking the CLI. 
It does not allow users to use only environment variables, but only config files. This does not comply with the instructions https://github.com/packethost/packet-cli#authentication

### PR DESCRIPTION
**Pull request by alexeldeib**
Fixes https://github.com/packethost/packet-cli/issues/20

Sorry! 😢 @jasmingacic

### CODE REVIEW

**Comment by jasmingacic** [comment]
@alexeldeib The fix seems to be ok. 
But the question is why do you need this implementation when the CLI was already accepting json and yaml config files?

**Comment by alexeldeib** [comment]
It wasn't accepting yaml files. That was the exact point of the fix.

**Comment by jasmingacic** [comment]
Yeah that makes sense. 
I would only replace this:
```
_ = viper.ReadInConfig()
```
with this
```
viper.ReadInConfig()
```

**Comment by alexeldeib** [comment]
I'm happy either way, it's uglier but I tend to prefer explicitly vs implicitly ignoring the error. Will let @t0mk decide preference since he's stuck maintaining it 😃

**Comment by t0mk** [comment]
Yes let's drop the undescore. I will do it.

If eveything is OK, shall we merge?

**Review by jasmingacic — APPROVED** [review]

**Comment by jasmingacic** [comment]
Go ahead get it merged.

**Pull request merged**
